# Generated by Django 4.1.5 on 2023-01-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.CharField(max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("address", models.CharField(max_length=300)),
                ("total_area", models.IntegerField()),
                ("rooms", models.IntegerField()),
                ("bed_rooms", models.IntegerField()),
                ("water", models.BooleanField()),
                ("internet", models.BooleanField()),
                ("tv", models.BooleanField()),
                ("gas", models.BooleanField()),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
            ],
        ),
    ]
